### ISSUE TITLE
Routes - Namespacing

### ISSUE THREAD

**Issue by gaelyn** [wdk3/knewharvest_be_api#26]
- [ ] Namespace under api/v1
- [ ] Don't forget to adjust controllers Api::V1::User and Api::V1::SubLocation

**Comment by kon-ham** [comment]
Working on this now

**Comment by kon-ham** [comment]
Gaelyn, here's what I've done so far or what I plan to do:

This is my routes file:
```
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :sub_locations
      resources :users
    end
  end
end
```
I've confirmed that name spacing works in the way we want based off a quick look through `rails routes`.

I intend to now create the directory pathway `app/controllers/api/v1/` in order to house `user_controller` and `sub_locations_controller`.

Was there something I was missing with the adjustment of the models files? I looked through my previous projects and I couldn't see if there was anything that needed to be changed for our name spacing...

Either way! I'll finish up creating these directories and see if I get word back from ya' or ya'll.

See you~

**Comment by kon-ham** [comment]
Here's the branch I've pushed with the work I've done so far: https://github.com/wdk3/knewharvest_be_api/tree/name_spacing

I am not yet ready to create a pull request because I want to get some feedback on the models situation in case I missed something.

Regards!

**Comment by kon-ham** [comment]
I think I've covered most of our name spacing, but all of our tests broke - was wondering if there was a way we could work around not having to do the tests until a bit later?

**Comment by gaelyn** [comment]
Yes, that’s perfect Kon. I’m sorry, I don’t know why I said to namespace the models 🤦🏻‍♀️

**Comment by gaelyn** [comment]
I do think the tests have to be nested though, is that why they’re breaking?

**Comment by kon-ham** [comment]
Hi Gaelyn, yeah seems like when I name spaced the tests they all broke immediately lmao. No worries about the model thing - just wanted to be sure.

**Comment by kon-ham** [comment]
Now that I think about it, I could just comment out our tests for now?

**Comment by gaelyn** [comment]
That's fine with me. We can always fix them in a separate PR.
